added 10-c
hse-cs-ami/caos-lectures pull request #11
Opened 2023-03-06 15:21 UTC by ann-vasileeva

2023-03-06 15:29 UTC, ann-vasileeva commented
Почему-то исходная лекция местами незначительно отформатировалась, я могу это поправить обратно

2023-03-16 18:02 UTC, ann-vasileeva commented
@avm , почему-то старый текст странно отформатировался, могу это поправить обратно

2023-03-17 13:45 UTC, avm requested changes

2023-03-17 13:45 UTC, avm commented on lectures/src/10-c/index.md
> +Исполнение начинается с нахождения функции main: если она не нашлась - ошибка компановки. Main - единственная функция, которая может ничего не возвращать, и это не приведет к UB. В таком случае будет
* компоновки
* считаться

2023-03-17 13:45 UTC, avm commented on lectures/src/10-c/index.md
> +Для статической переменной сообщает комплитору, что в других единицах трансляциях эту переменную нельзя увидеть (то есть переменная перестанет быть экспортируемой (так по умолчанию))
компилятору :-)

2023-03-17 13:45 UTC, avm commented on lectures/src/10-c/index.md
> +3. Смотрит специкатор формата
спецификатор

2023-03-17 13:45 UTC, avm commented on lectures/src/10-c/index.md
> +    - Пример: представление**Целые типы** целых чисел
тут вкрался заголовок откуда-то

2023-03-17 13:45 UTC, avm commented on lectures/src/10-c/index.md
> +![https://caos.myltsev.ru/lectures/10-c/kt-dr-pdp11.jpg](https://caos.myltsev.ru/lectures/10-c/kt-dr-pdp11.jpg)
Давайте такие случайно изменившиеся фрагменты попробуем откатить.

2023-03-17 14:42 UTC, ann-vasileeva commented on lectures/src/10-c/index.md
> +![https://caos.myltsev.ru/lectures/10-c/kt-dr-pdp11.jpg](https://caos.myltsev.ru/lectures/10-c/kt-dr-pdp11.jpg)
Вроде теперь все поправилось

2023-03-17 14:46 UTC, ann-vasileeva commented
@avm, исправила

2023-03-23 17:06 UTC, merged