Lecture notes on processes
hse-cs-ami/caos-lectures pull request #12
Opened 2023-03-07 15:57 UTC by EugeneDar

2023-03-10 13:45 UTC, EugeneDar commented
@avm please, have a look

2023-03-11 06:31 UTC, avm requested changes

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +  В `u` — подставки для ориентированных на пользователя формате, который обеспечивает подробную информацию о процессах.
Какие подставки? O_o

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +* *Процесс* — это система действий, реализующая определенную функцию в вычислительной системе и оформленная так, что управляющая программа вычислительной системы может перераспределять ресурсы этой с
Не понимаю, что такое "система действий".

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +* У процесса есть своя виртуальная память и таблица файловых дискрипторов.
дЕскрипторов

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +* Системный вызов `fork` - полностью копирует процесс, который его вызвал. Важно понимать, что хоть у них идентичные пространства виртуальной памяти, они всё же отдельные.
Давайте мы всё-таки под заголовком "как породить новый процесс" оставим только fork — остальные ничего не порождают.

Пространства виртуальной памяти *изначально* идентичные (сразу после копирования), но потом-то нет.

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +* Системный вызов `wait` приостанавливает выполнение вызывающего потока пока не завершится один из его дочерних потоков.
До потоков не добрались ещё, у нас пока процессы.

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +Что нужно знать про системный вызов `wait`? Если дочерний процесс уже завершился, а родительский ещё нет, то дочерний переход с состояние `zombie/defunct process`, так как понимает, что родительский
Кажется, голосовой ввод вас подводит.

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +  * struct file - уменьшение счётчика указателей
Нет.

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +Здесь мы имеем, что дочерний поток отдаст свои ресурсы под выполнение бинарного файла, а родительский продолжит выполнять свой код дальше. `wait` добавили, чтобы родительский процесс сначала дождался
wait дожидается завершения дочернего процесса, а не exec в нём.

2023-03-11 06:31 UTC, avm commented on lectures/src/19-process/index.md
> +Команда делает так, чтобы определенный файловый дескриптор (передаётся по номеру), смотрел туда же, куда и другой файловый дескприптор (тоже передаётся по номеру).
Не команда, а системный вызов.

2023-03-13 10:53 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +  В `u` — подставки для ориентированных на пользователя формате, который обеспечивает подробную информацию о процессах.
Fixed

2023-03-13 10:53 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +* *Процесс* — это система действий, реализующая определенную функцию в вычислительной системе и оформленная так, что управляющая программа вычислительной системы может перераспределять ресурсы этой с
Fixed

2023-03-13 10:55 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +* У процесса есть своя виртуальная память и таблица файловых дискрипторов.
Fixed

2023-03-13 11:01 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +* Системный вызов `fork` - полностью копирует процесс, который его вызвал. Важно понимать, что хоть у них идентичные пространства виртуальной памяти, они всё же отдельные.
Fixed

2023-03-13 11:02 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +* Системный вызов `wait` приостанавливает выполнение вызывающего потока пока не завершится один из его дочерних потоков.
Fixed

2023-03-13 11:05 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +Что нужно знать про системный вызов `wait`? Если дочерний процесс уже завершился, а родительский ещё нет, то дочерний переход с состояние `zombie/defunct process`, так как понимает, что родительский
Fixed

2023-03-13 11:06 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +  * struct file - уменьшение счётчика указателей
Fixed

2023-03-13 11:13 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +Команда делает так, чтобы определенный файловый дескриптор (передаётся по номеру), смотрел туда же, куда и другой файловый дескприптор (тоже передаётся по номеру).
Fixed

2023-03-13 11:13 UTC, EugeneDar commented on lectures/src/19-process/index.md
> +Здесь мы имеем, что дочерний поток отдаст свои ресурсы под выполнение бинарного файла, а родительский продолжит выполнять свой код дальше. `wait` добавили, чтобы родительский процесс сначала дождался
Fixed

2023-03-13 11:16 UTC, EugeneDar commented
@avm please, have a look again

2023-03-16 12:04 UTC, EugeneDar commented
@avm please, have a look again

2023-04-15 12:04 UTC, EugeneDar commented
@avm please, have a look again

2023-06-16 13:19 UTC, merged