interrupts
hse-cs-ami/caos-lectures pull request #4
Opened 2023-02-03 18:17 UTC by pashandor789

fixed interrupts

2023-02-04 06:04 UTC, avm requested changes
Только не делайте новый PR — надо просто запушить в ту же ветку, Github сам обновит PR.

2023-02-04 06:04 UTC, avm commented on lectures/src/interrupts/Interrupts.md
> +Пусть выполняется какая-то инструкция (например, mov) во время исполнения которой был взведён флаг IF (Interrupt flag), то есть процессор будет готов к обработке прерываний. Дальше процессор проверяе
> подключает прерывание инструкцией cli

Видимо, в лекции я сказал "отключает прерывания".

> таблицу с битами прерываний

С гейтами :-).

2023-02-04 14:02 UTC, pashandor789 commented
Исправлено!

2023-02-05 10:46 UTC, avm approved these changes

2023-02-05 10:46 UTC, merged