Lecture update
hse-cs-ami/caos-lectures pull request #6
Opened 2023-02-09 17:01 UTC by what-the-fawk

Fixed  noted problems

2023-02-09 17:45 UTC, avm requested changes

2023-02-09 17:45 UTC, avm commented on lectures/src/Rings of power/Кольца защиты.md
> +    При исполнении кода из какого-либо сегмента, процессор смотрит в таблицу дескрипторов сегментов, и подгружает в  cs новое значение из таблицы дескрипторов. Верхние 13 бит нового значения отвечают
> регистр понимает где смотреть дескрипторы

Давайте всё-таки успокоимся, выдохнем, перечитаем замечания к предыдущему PR и аккуратно напишем текст :-). Какое "значение из таблицы дескрипторов" загружается в `cs`?

2023-02-09 18:37 UTC, what-the-fawk commented on lectures/src/Rings of power/Кольца защиты.md
> +    При исполнении кода из какого-либо сегмента, процессор смотрит в таблицу дескрипторов сегментов, и подгружает в  cs новое значение из таблицы дескрипторов. Верхние 13 бит нового значения отвечают
Я немножечко не понял - откуда процессор берет новое значение cs - из GDT же?

2023-02-09 18:41 UTC, what-the-fawk commented on lectures/src/Rings of power/Кольца защиты.md
> +    При исполнении кода из какого-либо сегмента, процессор смотрит в таблицу дескрипторов сегментов, и подгружает в  cs новое значение из таблицы дескрипторов. Верхние 13 бит нового значения отвечают
У меня в голове пока примерно так - прежде чем начинается исполнение нового сегмента, процессор проверяет соответствие уровня привилегий, и если соответствие есть, то исполнение продолжается? Пересматриваю сейчас этот момент с лекции, слегка не понимаю

2023-02-09 19:06 UTC, what-the-fawk commented on lectures/src/Rings of power/Кольца защиты.md
> +    При исполнении кода из какого-либо сегмента, процессор смотрит в таблицу дескрипторов сегментов, и подгружает в  cs новое значение из таблицы дескрипторов. Верхние 13 бит нового значения отвечают
Если TPL не соответствует CPL - это сразу сегфолт? Хотелось бы узнать тайну всеи любимой ошибки

2023-02-09 19:11 UTC, what-the-fawk reviewed
YAFix

2023-02-10 09:50 UTC, avm commented on lectures/src/Rings of power/Кольца защиты.md
> +    При исполнении кода из какого-либо сегмента, процессор смотрит в таблицу дескрипторов сегментов, и подгружает в  cs новое значение из таблицы дескрипторов. Верхние 13 бит нового значения отвечают
[Вот тут](https://www.felixcloutier.com/x86/jmp#operation) есть такой псевдокод:
```
    IF (RPL > CPL) OR (DPL ≠ CPL)
            THEN #GP(code segment selector); FI;
```
То есть с точки зрения процессора это "General Protection fault", а уж дальше ОС выдаёт нам сегфолт, да.

2023-02-10 09:59 UTC, merged